### ISSUE TITLE
Compilation failed for libgraphqlparser (graphqlparser & lexer.cpp)

### ISSUE THREAD

**Issue by mazzi** [graphql/libgraphqlparser#107]
Trying to compile on MacOS 10.13.6
Flex: 2.6.4_1
Bison: 3.7.3

```
$ cmake .
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/2.7/bin/python2 (found suitable version "2.7.6", minimum required is "2")
-- Found BISON: /usr/local/opt/bison/bin/bison (found suitable version "3.7.3", minimum required is "3")
-- Found FLEX: /usr/local/opt/flex/bin/flex (found version "2.6.4")
CMake Warning at python/CMakeLists.txt:13 (MESSAGE):
  ctypesgen.py not found; install with pip or easy_install if you want to run
  pythontest.py.


-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.26")
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   graphqlparser

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /libgraphqlparser
```

And make

```
$ make
[  4%] [FLEX][GraphQLScanner] Building scanner with flex 2.6.4
make[2]: *** [lexer.cpp] Error 1
make[2]: *** Deleting file `lexer.cpp'
make[1]: *** [CMakeFiles/graphqlparser.dir/all] Error 2
make: *** [all] Error 2
$
```

Any clue on this? Thanks in advance!

**Comment by rprakash20** [comment]
Did you solve this ? @mazzi

**Comment by mazzi** [comment]
Hello @rprakash20
Didn't dig much. Decided to use docker instead 🤷‍♂️
